services:

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
    command: redis-server

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USERNAME:-root}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD:-root}"
    command: >
      sh -c "rabbitmq-plugins enable --offline \
      rabbitmq_amqp1_0 rabbitmq_management rabbitmq_web_dispatch rabbitmq_management_agent rabbitmq_stomp && \
      exec rabbitmq-server"
    volumes:
      - "./rabbitmq-config:/etc/rabbitmq"

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # jaeger UI
      - "4317:4317"   # collector grpc
      - "4318:4318"   # collector http
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  mongodb_data:
