server:
  port: 8080

logging:
  level:
    ROOT: info
    com.company.project: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    enabled: true

spring:
  main:
    banner-mode: log
  datasource:
    url: jdbc:postgresql://localhost:5432/pn_template_project
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 3
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/pn_template_project?authSource=admin
    redis:
      host: localhost
      port: 6379
      password:
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full

application:
  client:
    notification:
      url: http://localhost:8081